---
name: open-interfaces

channels:
    - conda-forge
    - defaults

dependencies:
    - python
    - pip
    - libblas=*=*_openblas
    - blas-devel
    - liblapacke
    - numpy
    - scipy
    - matplotlib
    - msgpack-python
    - cmake
    - c-compiler
    - cxx-compiler
    - fortran-compiler
    - sundials
